---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: green
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: django-k8s-demo
    app.kubernetes.io/managed-by: kubectl
  name: django-green
  namespace: blue-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: django
      app.kubernetes.io/instance: green
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django
        app.kubernetes.io/instance: green
    spec:
      containers:
        - image: ghcr.io/pasiol/django-k8s-demo-web@sha256:4d2b9f3191b27ff30a0e4eaf896887afeaddad60e0d71b7709f71e64233ca857
          name: django-k8s-demo-web
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "40Mi"
              cpu: "20m"
            limits:
              cpu: "80m"
              memory: "80Mi"
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: databaseName
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: host
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: allowedHosts
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: debug
      initContainers:
        - name: db-migrate
          image: ghcr.io/pasiol/django-k8s-demo-web@sha256:4d2b9f3191b27ff30a0e4eaf896887afeaddad60e0d71b7709f71e64233ca857
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "python manage.py makemigrations && python manage.py migrate"]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: databaseName
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: host
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: allowedHosts
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: debug
