---
apiVersion: v1
kind: Service
metadata:
  name: web-public
  namespace: blue-green
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000
  selector:
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: blue

