---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - protocol: TCP
      name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: blue-green
spec:
  selector:
    matchLabels:
      app: postgresql-server
  serviceName: db
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: postgresql-server
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: postgresql-server
        image: docker.io/library/postgres:16
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: databaseName
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: host
        resources:
            requests:
              memory: "40Mi"
              cpu: "20m"
            limits:
              cpu: "200m"
              memory: "200Mi"
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: db-volume
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 1Gi
