---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: blue-green
spec:
  containers:
    - image: quay.io/almalinuxorg/9-base:latest
      command:
        - sleep
        - "43200"
      imagePullPolicy: IfNotPresent
      name: toolbox
      resources:
        requests:
          memory: "100Mi"
          cpu: "50m"
        limits:
          memory: "200Mi"
  restartPolicy: Always
