version: '3'

services:
  postgres:
    image: postgres_dk8sdemo
    build: postgres
    volumes:
      - .postgres-volume:/var/lib/postgresql/data
  web:
    build: django_app/
    image: ghcr.io/pasiol/django-k8s-demo-web:latest
    environment:
      POSTGRES_USER: dk8sdemo
      POSTGRES_PASSWORD: dk8sdemo
      POSTGRES_DB: dk8sdemo
      POSTGRES_HOST: postgres
      DJANGO_DEBUG: "true"
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - '8000:8000'
    depends_on:
      - postgres
volumes:
  postgres-volume:
