version: '3'

services:
  postgres:
    image: postgres_dk8sdemo
    build: postgres
    volumes:
      - .postgres-volume:/var/lib/postgresql/data
  web:
    build: .
    environment:
      POSTGRES_USER: dk8sdemo
      POSTGRES_PASSWORD: dk8sdemo
      POSTGRES_DB: dk8sdemo
      POSTGRES_HOST: postgres
      ALLOWED_HOSTS: '127.0.0.1'
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - postgres
volumes:
  postgres-volume:
