# Generated by Django 3.1.14 on 2022-05-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128)),
                ('fqdn', models.CharField(max_length=256)),
                ('ip_address', models.CharField(max_length=32)),
                ('mac_address', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('worker_id', 'mac_address')},
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_agent', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinfo.worker')),
            ],
        ),
    ]
