# Generated by Django 2.2 on 2019-09-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='source',
            new_name='user_agent',
        ),
    ]
