# Generated by Django 3.1.14 on 2022-05-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='mac_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
