# Generated by Django 3.1.14 on 2022-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0002_auto_20220523_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='mac_address',
            field=models.CharField(max_length=17),
        ),
    ]
