---
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: simple-deployment
  labels:
    app.kubernetes.io/name: debug-pod
    app.kubernetes.io/instance: almalinux-base
    app.kubernetes.io/version: "9"
    app.kubernetes.io/component: debug-container
    app.kubernetes.io/part-of: django-k8s-demo
    app.kubernetes.io/managed-by: kubectl
spec:
  containers:
    - image: ghcr.io/pasiol/debug-pod-k8s-demo@sha256:22f67916965085d915619dd356e225ba1152199708cca8a75acdd74a4e7903a7
      command:
        - sleep
        - "43200"
      imagePullPolicy: IfNotPresent
      name: toolbox
      resources: {}
  restartPolicy: Always
