---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: simple-deployment
spec:
  limits:
  - type: Container
    default:
      memory: "40Mi"
      cpu: "20m"
    defaultRequest:
      memory: "20Mi"
      cpu: "10m"
    max:
      memory: "200Mi"
      cpu: "200m"
    min:
      memory: "10Mi"
      cpu: "2m"
  - type: PersistentVolumeClaim
    max:
      storage: 1Gi
    min:
      storage: 10Mi