apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  labels:
    app: toolbox
  namespace: django-k8s-demo
spec:
  containers:
    - image: debian:bullseye-slim
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: toolbox