apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ns.yaml
  - postgres/volume.yaml
  - postgres/volume_claim.yaml
  - postgres/secrets.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - django/deployment.yaml
  - django/make_migrations.yaml
  - django/migrate.yaml
  - django/service.yaml
  - debugContainer.yaml