---
apiVersion: v1
kind: Service
metadata:
  namespace: django-k8s-demo
  name: dk8sdemo-web
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000
  selector:
    app: dk8sdemo-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dk8sdemo-web
  name: dk8sdemo-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dk8sdemo-web
  template:
    metadata:
      labels:
        app: dk8sdemo-web
    spec:
      containers:
        - name: django-k8s-demo-web
          image: ghcr.io/pasiol/django-k8s-demo-web:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: dk8sdemo
            - name: POSTGRES_PASSWORD
              value: dk8sdemo
            - name: POSTGRES_DB
              value: dk8sdemo
            - name: POSTGRES_HOST
              value: dk8sdemo-db
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
            - name: DJANGO_DEBUG
              value: "True"
      initContainers:
        - name: db-migrate
          image: ghcr.io/pasiol/django-k8s-demo-web:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "python manage.py makemigrations && python manage.py migrate"]
          env:
            - name: POSTGRES_USER
              value: dk8sdemo
            - name: POSTGRES_PASSWORD
              value: dk8sdemo
            - name: POSTGRES_DB
              value: dk8sdemo
            - name: POSTGRES_HOST
              value: dk8sdemo-db
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
