# Generated by Django 3.1.14 on 2023-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['hostname'], name='cinfo_worke_hostnam_e66498_idx'),
        ),
    ]
