apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:11
          name: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-db-data-pvc
              mountPath: /var/lib/postgresql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password

            - name: POSTGRES_DB
              value: dk8sdemo
      volumes:
        - name: postgres-db-data-pvc
