apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - name: db
      port: 5432
      targetPort: 5432
