FROM postgres:15
RUN localedef -i fi_FI -c -f UTF-8 -A /usr/share/locale/locale.alias fi_FI.UTF-8
ENV LANG fi_FI.utf8
ENV POSTGRES_USER dk8sdemo
ENV POSTGRES_PASSWORD dk8sdemo
ENV POSTGRES_DB dk8sdemo