apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk8sdemo
  namespace: django-k8s-demo
  labels:
    app: dk8sdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: dk8ksdemo
  template:
    metadata:
      labels:
        pod: dk8ksdemo
    spec:
      containers:
        - name: dk8sdemo
          image: pasiol/dk8sdemo@sha256:d0f86d3084a30675ea3a70f59836e96c78ebf3a39f157226bfaa0aba7ec1c4b1
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRES_HOST
              value: postgres-service
            - name: DJANGO_ALLOWED_HOSTS
              value: "10.0.3.1"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 5

