apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: django-k8s-demo
spec:
  selector:
    app: postgres-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
