apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: django-k8s-demo
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres-pv
